version: '3.1'

services:
  frontend:
    build:
      context: UI
    environment:
      API_SERVER: http://backend
      DELAY: 0
    ports:
      - 3000:3000

  backend:
    build: 
      context: API
      dockerfile: ToDo.Api/Dockerfile
    environment:
      - ConnectionStrings:MongoDb=mongodb://$MONGO_ROOT_USERNAME:$MONGO_ROOT_PASSWORD@mongo:27017/
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 3001:80

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ROOT_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_ROOT_USERNAME:$MONGO_ROOT_PASSWORD@mongo:27017/
